@startuml

class users {
    <b>user_id</b> （用户ID）
    name （用户真实姓名）
    github_username （用户GitHub账号）
    update_date （用户GitHub账号修改日期）
    password （用户密码）
    disable （用户是否禁用）
}

class course{
    <b>course_id</b>(课程编号)
    course_name(课程名称)
}
users "n" -"n" course

@enduml